### PR TITLE
Remove extra layers

### PR DESCRIPTION
**Pull request by e111077**
[Without Whitespace changes](https://github.com/PolymerElements/polymon/pull/106/files?w=1)

Removed layers by creating some render controlling elements.

| new | old |
| - | - |
| image | image |

Render controlling is completely opt-in. You must have either a `<polymon-multi-pages>` or a `PolymerMultiPagesBehavior` plus a child element that has `PolymonRenderableBehavior` and a `page-name`. If any of these are missing, then an element will not be managed by the `polymon-multi-pages`.

Example:
```html
<polymon-multi-pages
    selected-values="[[renderedPages]]">
  <has-renderable-behavior
      page-name="firstPage">
  </has-renderable-behavior>
  <has-renderable-behavior
      page-name="secondPage">
  </has-renderable-behavior>
  <has-renderable-behavior
      page-name="thirdPage">
  </has-renderable-behavior>
</polymon-multi-pages>
<script>
  Polymer({
    ...
    properties: {
      renderedPages: {
        value: _ => {
          return ['firstPage', 'thirdPage']
        }
      }
    });
</script>
```

Renderable elements have a `render` function that defaults to setting `[hidden]` on the host by default (`render()` or `render(false)`) unless `render(true)` is called. Render functions can be overridden. See `polymon-polydex.html`.

The render controller will give a `console.error` if a child does not have a `.render` function yet is selectable (has `page-map` attribute).

### CODE REVIEW

**Review by bicknellr — COMMENTED** [review]
Just adding a few nitpicky things at the moment since I don't think I've wrapped my head around the PR yet. :) AFAICT, `polymon-render-controller` is controlling a `hidden` property on descendants with `PolymonRenderableBehavior` based on its `siteMap`?

Also, I noticed a lot of seemingly-extra lines but then realized that they're almost all before `else` - maybe this is just a code style thing I'm not used to?

**Review by bicknellr — CHANGES_REQUESTED** [review]
Here's some extra elements being rendered - probably worth double checking though to make sure I didn't forget that the top background was being used in these cases. I'm still looking through the rest of this PR.

**Review by bicknellr — APPROVED** [review]
LGTM, but I'd wait for @cdata too. Also, I opened a PR based on this branch (#143) that removes the polydex's customized render function by using `:host([hidden]) > *` instead of `:host([hidden])` so it can hide its contents using without also removing its own box and screwing up the panel layout; PTAL.

**Review by cdata — CHANGES_REQUESTED** [review]
All in all, I'm still worried that this change is on the ambitious side. I'll be around this evening if you have time to reply to the feedback today.

**Comment by cdata** [comment]
I'm gonna close this PR for now, and we can revisit it if Polymon happens to come up down the road. Thanks for your hard work on this topic.

**Pull request closed without merging**
